######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 14 22:16:41 2011
######################################################################

QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += link_pkgconfig
PKGCONFIG += libavcodec libavformat libavutil libswscale sdl SDL_mixer SimpleAV_SDL

CFLAGS += -g -O2 -Wall -W

# Input
HEADERS += GLPlayerWindow.hpp
SOURCES += GLPlayerWindow.cpp main.cpp
